/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/e8PHNf1FJdf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from '@components/ui/button';
import Modal from 'react-modal';
import { AppleIcon, ChromeIcon, FacebookIcon, MailIcon, NavigationIcon } from '@components/ui/icon';
import GoogleLoginButton from '@components/login/GoogleLoginButton';
import { useState } from 'react';
import SignUpModal from './SignUpModal';

Modal.setAppElement('#__next');

const customModalStyles = {
  content: {
    top: '50%',
    left: '50%',
    right: 'auto',
    bottom: 'auto',
    marginRight: '-50%',
    transform: 'translate(-50%, -50%)',
    padding: '20px',
  },
};
interface ISignupModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const LoginModal = ({ isOpen, onClose }: ISignupModalProps) => {
  const [signUpOpen, setSignUpOpen] = useState<Boolean>(false);
  const SignUpOpen = () => {
    setSignUpOpen(true);
  };
  return (
    <>
      <Modal
        role={'dialog'}
        isOpen={isOpen}
        onRequestClose={onClose}
        shouldCloseOnOverlayClick={true}
        style={customModalStyles}
      >
        <div className="max-w-md mx-auto">
          <div className="text-right">
            <Button className="text-sm" variant="ghost" onClick={onClose}>
              X
            </Button>
            <Button className="text-sm" variant="ghost" onClick={SignUpOpen}>
              로그인 또는 회원 가입
            </Button>
          </div>
          <div className="mt-6 text-center">
            <h1 className="text-2xl font-bold">Wellcome to salon sotre</h1>
            <p className="mt-2 text-sm text-gray-600">
              예약을 이용하기 위해서는 로그인 필요합니다.
            </p>
          </div>

          <div className="mt-6">
            <div className="border-t border-gray-300" />
            <div className="flex flex-col space-y-4 mt-4">
              {/* Google login*/}
              <GoogleLoginButton />
              {/* Facebook login*/}
              <Button className="flex items-center justify-around space-x-2" variant="secondary">
                <FacebookIcon className="w-6 h-6 text-blue-600" />
                <span>페이스북으로 로그인하기</span>
              </Button>
              {/* Apple login */}
              <Button className="flex items-center justify-around space-x-5" variant="secondary">
                <AppleIcon className="w-6 h-6" />
                <span>애플로 로그인하기</span>
              </Button>
              {/* Email login */}
              <Button className="flex items-center justify-around space-x-2" variant="secondary">
                <MailIcon className="w-6 h-6" />
                <span>이메일로 로그인하기</span>
              </Button>
            </div>
          </div>
        </div>
      </Modal>
    </>
  );
};

export default LoginModal;
